# Generated by Django 3.1.7 on 2021-03-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forza', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
